language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $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
 local_dir: dist
 on:
   branch: main
